Cosmetic: improve exception traceback readability
python-humanize/humanize pull request #80
Opened 2022-12-27 11:42 UTC by hugovk

Changes proposed in this pull request:

* Assign exception messages to a temporary variable first, to make tracebacks easier to read
* See https://github.com/henryiii/flake8-errmsg

2022-12-29 01:32 UTC, carterbox requested changes
Might as well fix some grammar while we're here. Otherwise, LGTM. I agree that this PR improves traceback readability.

2022-12-29 01:32 UTC, carterbox commented on src/humanize/time.py
> +        msg = f"Minimum unit '{minimum_unit}' not supported"
```suggestion
        msg = f"Minimum unit '{minimum_unit}' not supported."
```

2022-12-29 01:32 UTC, carterbox commented on src/humanize/time.py
> +        msg = "Minimum unit is suppressed and no suitable replacement was found"
```suggestion
        msg = "Minimum unit is suppressed, and no suitable replacement was found."
```

2022-12-30 22:03 UTC, hugovk commented
I think the single sentence exception messages are fine without a full stop at the end. If there are two or more sentences, then it's needed.

A quick search of CPython source code suggests the vast majority (~95%) do not end with a full stop:

```console
$ # Ending with a full stop
$ git grep "raise .*Error(.*\.['\"])" Lib | wc -l
      79
$ # Ending with no full stop
$ git grep "raise .*Error(.*[^\.]['\"])" Lib | wc -l
    1609
```

2023-01-07 16:32 UTC, merged